### ISSUE TITLE
Add Travis CI support for this repository

### ISSUE THREAD

**Issue by astorije** [thelounge/thelounge.github.io#5]
[Configuring a third-party service to display Jekyll build error messages](https://help.github.com/articles/troubleshooting-github-pages-build-failures/#configuring-a-third-party-service-to-display-jekyll-build-error-messages)

**Comment by xPaw** [comment]
Something like this should do:
```yaml
language: ruby
rvm:
- 2.2

install:
- gem install jekyll html-proofer

script:
- jekyll build
- htmlproofer ./_site

# speeds up installation of html-proofer
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
```

https://jekyllrb.com/docs/continuous-integration/
